### PR TITLE
Modify node type to interface{}. Add go module.

### PR DESCRIPTION
**Pull request by cxt90730**

### CODE REVIEW

**Comment by vedhavyas** [comment]
Apologies for the delay.
Any specific usecase for `string` to `interface{}`?

**Comment by cxt90730** [comment]
I consider that in some specific cases, more node information needs to be stored, and type `struct` or `interface{}` may be used.

**Comment by vedhavyas** [comment]
Since we use it as key for the map, the key type has to satisfy the equality else it won't work. I think it is best to keep the string as is and the caller can map the string to spcific object

**Comment by cxt90730** [comment]
I know. In fact, as you said, I can maintain another map to achieve the same effect. I just personally think that the type `interface{}` can be more concise. Thank you for your reply.

**Comment by vedhavyas** [comment]
@cxt90730 would you still like to give a PR with modules ?

**Pull request closed without merging**
